// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: wallet/messages.proto

/* eslint-disable */
import { CHAIN, Wallet, WalletToken } from "../common/common";

export const protobufPackage = "wallet";

export enum DataType {
  API = "API",
  SCANNER = "SCANNER",
}

export interface AddWalletRequest {
  walletAddress: string;
}

export interface AddWalletResponse {
  success: boolean;
}

export interface GetWalletRequest {
  walletAddress: string;
  chain: CHAIN;
  type: DataType;
  tokenAddresses: string[];
}

export interface GetWalletResponse {
  walletData: Wallet | undefined;
}

export interface GetWalletTokensRequest {
  walletAddress: string;
  chain: CHAIN;
  type: DataType;
  tokenAddresses: string[];
  filterLowUSD: boolean;
}

export interface GetWalletTokensResponse {
  tokens: WalletToken[];
  numberOfTokens: number;
}

export interface GetWalletDetailsRequest {
  walletAddress: string;
  chain: CHAIN;
  type: DataType;
  tokenAddresses: string[];
  filterLowUSD: boolean;
}

export interface GetWalletDetailsResponse {
  tokens: WalletToken[];
  numberOfTokens: number;
  walletData: Wallet | undefined;
}

export interface UpdateWalletPortfolioRequest {
  walletAddress: string;
  totalDollarValue: string;
}

export interface UpdateWalletPortfolioResponse {
  success: boolean;
}

export const WALLET_PACKAGE_NAME = "wallet";
