// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: wallet/wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  AddWalletRequest,
  AddWalletResponse,
  GetWalletDetailsRequest,
  GetWalletDetailsResponse,
  GetWalletRequest,
  GetWalletResponse,
  GetWalletTokensRequest,
  GetWalletTokensResponse,
  UpdateWalletPortfolioRequest,
  UpdateWalletPortfolioResponse,
} from "./messages";

export const protobufPackage = "scanner_wallet";

export const SCANNER_WALLET_PACKAGE_NAME = "scanner_wallet";

export interface ScannerWalletClient {
  addWallet(request: AddWalletRequest): Observable<AddWalletResponse>;

  getWallet(request: GetWalletRequest): Observable<GetWalletResponse>;

  getWalletTokens(request: GetWalletTokensRequest): Observable<GetWalletTokensResponse>;

  getWalletDetails(request: GetWalletDetailsRequest): Observable<GetWalletDetailsResponse>;

  updateWalletPortfolio(request: UpdateWalletPortfolioRequest): Observable<UpdateWalletPortfolioResponse>;
}

export interface ScannerWalletController {
  addWallet(request: AddWalletRequest): Promise<AddWalletResponse> | Observable<AddWalletResponse> | AddWalletResponse;

  getWallet(request: GetWalletRequest): Promise<GetWalletResponse> | Observable<GetWalletResponse> | GetWalletResponse;

  getWalletTokens(
    request: GetWalletTokensRequest,
  ): Promise<GetWalletTokensResponse> | Observable<GetWalletTokensResponse> | GetWalletTokensResponse;

  getWalletDetails(
    request: GetWalletDetailsRequest,
  ): Promise<GetWalletDetailsResponse> | Observable<GetWalletDetailsResponse> | GetWalletDetailsResponse;

  updateWalletPortfolio(
    request: UpdateWalletPortfolioRequest,
  ): Promise<UpdateWalletPortfolioResponse> | Observable<UpdateWalletPortfolioResponse> | UpdateWalletPortfolioResponse;
}

export function ScannerWalletControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "addWallet",
      "getWallet",
      "getWalletTokens",
      "getWalletDetails",
      "updateWalletPortfolio",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ScannerWallet", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ScannerWallet", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SCANNER_WALLET_SERVICE_NAME = "ScannerWallet";
