// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: wallet/messages.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "walletdata/proto/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_API     DataType = 0
	DataType_SCANNER DataType = 1
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "API",
		1: "SCANNER",
	}
	DataType_value = map[string]int32{
		"API":     0,
		"SCANNER": 1,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_wallet_messages_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_wallet_messages_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{0}
}

type AddWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWalletRequest) Reset() {
	*x = AddWalletRequest{}
	mi := &file_wallet_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWalletRequest) ProtoMessage() {}

func (x *AddWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWalletRequest.ProtoReflect.Descriptor instead.
func (*AddWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AddWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type AddWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWalletResponse) Reset() {
	*x = AddWalletResponse{}
	mi := &file_wallet_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWalletResponse) ProtoMessage() {}

func (x *AddWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWalletResponse.ProtoReflect.Descriptor instead.
func (*AddWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AddWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetWalletRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress  string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	Chain          common.CHAIN           `protobuf:"varint,2,opt,name=chain,proto3,enum=common.CHAIN" json:"chain,omitempty"`
	Type           DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=wallet.DataType" json:"type,omitempty"`
	TokenAddresses []string               `protobuf:"bytes,4,rep,name=tokenAddresses,proto3" json:"tokenAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetWalletRequest) GetChain() common.CHAIN {
	if x != nil {
		return x.Chain
	}
	return common.CHAIN(0)
}

func (x *GetWalletRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_API
}

func (x *GetWalletRequest) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletData    *common.Wallet         `protobuf:"bytes,1,opt,name=walletData,proto3" json:"walletData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_wallet_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletResponse) GetWalletData() *common.Wallet {
	if x != nil {
		return x.WalletData
	}
	return nil
}

type GetWalletTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress  string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	Chain          common.CHAIN           `protobuf:"varint,2,opt,name=chain,proto3,enum=common.CHAIN" json:"chain,omitempty"`
	Type           DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=wallet.DataType" json:"type,omitempty"`
	TokenAddresses []string               `protobuf:"bytes,4,rep,name=tokenAddresses,proto3" json:"tokenAddresses,omitempty"`
	FilterLowUSD   bool                   `protobuf:"varint,5,opt,name=filterLowUSD,proto3" json:"filterLowUSD,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWalletTokensRequest) Reset() {
	*x = GetWalletTokensRequest{}
	mi := &file_wallet_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTokensRequest) ProtoMessage() {}

func (x *GetWalletTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTokensRequest.ProtoReflect.Descriptor instead.
func (*GetWalletTokensRequest) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletTokensRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetWalletTokensRequest) GetChain() common.CHAIN {
	if x != nil {
		return x.Chain
	}
	return common.CHAIN(0)
}

func (x *GetWalletTokensRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_API
}

func (x *GetWalletTokensRequest) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

func (x *GetWalletTokensRequest) GetFilterLowUSD() bool {
	if x != nil {
		return x.FilterLowUSD
	}
	return false
}

type GetWalletTokensResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tokens         []*common.WalletToken  `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	NumberOfTokens int32                  `protobuf:"varint,2,opt,name=numberOfTokens,proto3" json:"numberOfTokens,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWalletTokensResponse) Reset() {
	*x = GetWalletTokensResponse{}
	mi := &file_wallet_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTokensResponse) ProtoMessage() {}

func (x *GetWalletTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTokensResponse.ProtoReflect.Descriptor instead.
func (*GetWalletTokensResponse) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetWalletTokensResponse) GetTokens() []*common.WalletToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *GetWalletTokensResponse) GetNumberOfTokens() int32 {
	if x != nil {
		return x.NumberOfTokens
	}
	return 0
}

type GetWalletDetailsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress  string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	Chain          common.CHAIN           `protobuf:"varint,2,opt,name=chain,proto3,enum=common.CHAIN" json:"chain,omitempty"`
	Type           DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=wallet.DataType" json:"type,omitempty"`
	TokenAddresses []string               `protobuf:"bytes,4,rep,name=tokenAddresses,proto3" json:"tokenAddresses,omitempty"`
	FilterLowUSD   bool                   `protobuf:"varint,5,opt,name=filterLowUSD,proto3" json:"filterLowUSD,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWalletDetailsRequest) Reset() {
	*x = GetWalletDetailsRequest{}
	mi := &file_wallet_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDetailsRequest) ProtoMessage() {}

func (x *GetWalletDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletDetailsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetWalletDetailsRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetWalletDetailsRequest) GetChain() common.CHAIN {
	if x != nil {
		return x.Chain
	}
	return common.CHAIN(0)
}

func (x *GetWalletDetailsRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_API
}

func (x *GetWalletDetailsRequest) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

func (x *GetWalletDetailsRequest) GetFilterLowUSD() bool {
	if x != nil {
		return x.FilterLowUSD
	}
	return false
}

type GetWalletDetailsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tokens         []*common.WalletToken  `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	NumberOfTokens int32                  `protobuf:"varint,2,opt,name=numberOfTokens,proto3" json:"numberOfTokens,omitempty"`
	WalletData     *common.Wallet         `protobuf:"bytes,3,opt,name=walletData,proto3" json:"walletData,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWalletDetailsResponse) Reset() {
	*x = GetWalletDetailsResponse{}
	mi := &file_wallet_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDetailsResponse) ProtoMessage() {}

func (x *GetWalletDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletDetailsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletDetailsResponse) GetTokens() []*common.WalletToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *GetWalletDetailsResponse) GetNumberOfTokens() int32 {
	if x != nil {
		return x.NumberOfTokens
	}
	return 0
}

func (x *GetWalletDetailsResponse) GetWalletData() *common.Wallet {
	if x != nil {
		return x.WalletData
	}
	return nil
}

type UpdateWalletPortfolioRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress    string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	TotalDollarValue string                 `protobuf:"bytes,2,opt,name=totalDollarValue,proto3" json:"totalDollarValue,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateWalletPortfolioRequest) Reset() {
	*x = UpdateWalletPortfolioRequest{}
	mi := &file_wallet_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletPortfolioRequest) ProtoMessage() {}

func (x *UpdateWalletPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletPortfolioRequest.ProtoReflect.Descriptor instead.
func (*UpdateWalletPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWalletPortfolioRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *UpdateWalletPortfolioRequest) GetTotalDollarValue() string {
	if x != nil {
		return x.TotalDollarValue
	}
	return ""
}

type UpdateWalletPortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletPortfolioResponse) Reset() {
	*x = UpdateWalletPortfolioResponse{}
	mi := &file_wallet_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletPortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletPortfolioResponse) ProtoMessage() {}

func (x *UpdateWalletPortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletPortfolioResponse.ProtoReflect.Descriptor instead.
func (*UpdateWalletPortfolioResponse) Descriptor() ([]byte, []int) {
	return file_wallet_messages_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateWalletPortfolioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_wallet_messages_proto protoreflect.FileDescriptor

const file_wallet_messages_proto_rawDesc = "" +
	"\n" +
	"\x15wallet/messages.proto\x12\x06wallet\x1a\x13common/common.proto\"8\n" +
	"\x10AddWalletRequest\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\"-\n" +
	"\x11AddWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xab\x01\n" +
	"\x10GetWalletRequest\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\x12#\n" +
	"\x05chain\x18\x02 \x01(\x0e2\r.common.CHAINR\x05chain\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.wallet.DataTypeR\x04type\x12&\n" +
	"\x0etokenAddresses\x18\x04 \x03(\tR\x0etokenAddresses\"C\n" +
	"\x11GetWalletResponse\x12.\n" +
	"\n" +
	"walletData\x18\x01 \x01(\v2\x0e.common.WalletR\n" +
	"walletData\"\xd5\x01\n" +
	"\x16GetWalletTokensRequest\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\x12#\n" +
	"\x05chain\x18\x02 \x01(\x0e2\r.common.CHAINR\x05chain\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.wallet.DataTypeR\x04type\x12&\n" +
	"\x0etokenAddresses\x18\x04 \x03(\tR\x0etokenAddresses\x12\"\n" +
	"\ffilterLowUSD\x18\x05 \x01(\bR\ffilterLowUSD\"n\n" +
	"\x17GetWalletTokensResponse\x12+\n" +
	"\x06tokens\x18\x01 \x03(\v2\x13.common.WalletTokenR\x06tokens\x12&\n" +
	"\x0enumberOfTokens\x18\x02 \x01(\x05R\x0enumberOfTokens\"\xd6\x01\n" +
	"\x17GetWalletDetailsRequest\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\x12#\n" +
	"\x05chain\x18\x02 \x01(\x0e2\r.common.CHAINR\x05chain\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.wallet.DataTypeR\x04type\x12&\n" +
	"\x0etokenAddresses\x18\x04 \x03(\tR\x0etokenAddresses\x12\"\n" +
	"\ffilterLowUSD\x18\x05 \x01(\bR\ffilterLowUSD\"\x9f\x01\n" +
	"\x18GetWalletDetailsResponse\x12+\n" +
	"\x06tokens\x18\x01 \x03(\v2\x13.common.WalletTokenR\x06tokens\x12&\n" +
	"\x0enumberOfTokens\x18\x02 \x01(\x05R\x0enumberOfTokens\x12.\n" +
	"\n" +
	"walletData\x18\x03 \x01(\v2\x0e.common.WalletR\n" +
	"walletData\"p\n" +
	"\x1cUpdateWalletPortfolioRequest\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\x12*\n" +
	"\x10totalDollarValue\x18\x02 \x01(\tR\x10totalDollarValue\"9\n" +
	"\x1dUpdateWalletPortfolioResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess* \n" +
	"\bDataType\x12\a\n" +
	"\x03API\x10\x00\x12\v\n" +
	"\aSCANNER\x10\x01B\x19Z\x17walletdata/proto/walletb\x06proto3"

var (
	file_wallet_messages_proto_rawDescOnce sync.Once
	file_wallet_messages_proto_rawDescData []byte
)

func file_wallet_messages_proto_rawDescGZIP() []byte {
	file_wallet_messages_proto_rawDescOnce.Do(func() {
		file_wallet_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_messages_proto_rawDesc), len(file_wallet_messages_proto_rawDesc)))
	})
	return file_wallet_messages_proto_rawDescData
}

var file_wallet_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wallet_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wallet_messages_proto_goTypes = []any{
	(DataType)(0),                         // 0: wallet.DataType
	(*AddWalletRequest)(nil),              // 1: wallet.AddWalletRequest
	(*AddWalletResponse)(nil),             // 2: wallet.AddWalletResponse
	(*GetWalletRequest)(nil),              // 3: wallet.GetWalletRequest
	(*GetWalletResponse)(nil),             // 4: wallet.GetWalletResponse
	(*GetWalletTokensRequest)(nil),        // 5: wallet.GetWalletTokensRequest
	(*GetWalletTokensResponse)(nil),       // 6: wallet.GetWalletTokensResponse
	(*GetWalletDetailsRequest)(nil),       // 7: wallet.GetWalletDetailsRequest
	(*GetWalletDetailsResponse)(nil),      // 8: wallet.GetWalletDetailsResponse
	(*UpdateWalletPortfolioRequest)(nil),  // 9: wallet.UpdateWalletPortfolioRequest
	(*UpdateWalletPortfolioResponse)(nil), // 10: wallet.UpdateWalletPortfolioResponse
	(common.CHAIN)(0),                     // 11: common.CHAIN
	(*common.Wallet)(nil),                 // 12: common.Wallet
	(*common.WalletToken)(nil),            // 13: common.WalletToken
}
var file_wallet_messages_proto_depIdxs = []int32{
	11, // 0: wallet.GetWalletRequest.chain:type_name -> common.CHAIN
	0,  // 1: wallet.GetWalletRequest.type:type_name -> wallet.DataType
	12, // 2: wallet.GetWalletResponse.walletData:type_name -> common.Wallet
	11, // 3: wallet.GetWalletTokensRequest.chain:type_name -> common.CHAIN
	0,  // 4: wallet.GetWalletTokensRequest.type:type_name -> wallet.DataType
	13, // 5: wallet.GetWalletTokensResponse.tokens:type_name -> common.WalletToken
	11, // 6: wallet.GetWalletDetailsRequest.chain:type_name -> common.CHAIN
	0,  // 7: wallet.GetWalletDetailsRequest.type:type_name -> wallet.DataType
	13, // 8: wallet.GetWalletDetailsResponse.tokens:type_name -> common.WalletToken
	12, // 9: wallet.GetWalletDetailsResponse.walletData:type_name -> common.Wallet
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_wallet_messages_proto_init() }
func file_wallet_messages_proto_init() {
	if File_wallet_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_messages_proto_rawDesc), len(file_wallet_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wallet_messages_proto_goTypes,
		DependencyIndexes: file_wallet_messages_proto_depIdxs,
		EnumInfos:         file_wallet_messages_proto_enumTypes,
		MessageInfos:      file_wallet_messages_proto_msgTypes,
	}.Build()
	File_wallet_messages_proto = out.File
	file_wallet_messages_proto_goTypes = nil
	file_wallet_messages_proto_depIdxs = nil
}
