// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: wallet/wallet.proto

package wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScannerWallet_AddWallet_FullMethodName             = "/scanner_wallet.ScannerWallet/addWallet"
	ScannerWallet_GetWallet_FullMethodName             = "/scanner_wallet.ScannerWallet/getWallet"
	ScannerWallet_GetWalletTokens_FullMethodName       = "/scanner_wallet.ScannerWallet/getWalletTokens"
	ScannerWallet_GetWalletDetails_FullMethodName      = "/scanner_wallet.ScannerWallet/getWalletDetails"
	ScannerWallet_UpdateWalletPortfolio_FullMethodName = "/scanner_wallet.ScannerWallet/updateWalletPortfolio"
)

// ScannerWalletClient is the client API for ScannerWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerWalletClient interface {
	AddWallet(ctx context.Context, in *AddWalletRequest, opts ...grpc.CallOption) (*AddWalletResponse, error)
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	GetWalletTokens(ctx context.Context, in *GetWalletTokensRequest, opts ...grpc.CallOption) (*GetWalletTokensResponse, error)
	GetWalletDetails(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*GetWalletDetailsResponse, error)
	UpdateWalletPortfolio(ctx context.Context, in *UpdateWalletPortfolioRequest, opts ...grpc.CallOption) (*UpdateWalletPortfolioResponse, error)
}

type scannerWalletClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerWalletClient(cc grpc.ClientConnInterface) ScannerWalletClient {
	return &scannerWalletClient{cc}
}

func (c *scannerWalletClient) AddWallet(ctx context.Context, in *AddWalletRequest, opts ...grpc.CallOption) (*AddWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWalletResponse)
	err := c.cc.Invoke(ctx, ScannerWallet_AddWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerWalletClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, ScannerWallet_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerWalletClient) GetWalletTokens(ctx context.Context, in *GetWalletTokensRequest, opts ...grpc.CallOption) (*GetWalletTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletTokensResponse)
	err := c.cc.Invoke(ctx, ScannerWallet_GetWalletTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerWalletClient) GetWalletDetails(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*GetWalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletDetailsResponse)
	err := c.cc.Invoke(ctx, ScannerWallet_GetWalletDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerWalletClient) UpdateWalletPortfolio(ctx context.Context, in *UpdateWalletPortfolioRequest, opts ...grpc.CallOption) (*UpdateWalletPortfolioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWalletPortfolioResponse)
	err := c.cc.Invoke(ctx, ScannerWallet_UpdateWalletPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerWalletServer is the server API for ScannerWallet service.
// All implementations must embed UnimplementedScannerWalletServer
// for forward compatibility.
type ScannerWalletServer interface {
	AddWallet(context.Context, *AddWalletRequest) (*AddWalletResponse, error)
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	GetWalletTokens(context.Context, *GetWalletTokensRequest) (*GetWalletTokensResponse, error)
	GetWalletDetails(context.Context, *GetWalletDetailsRequest) (*GetWalletDetailsResponse, error)
	UpdateWalletPortfolio(context.Context, *UpdateWalletPortfolioRequest) (*UpdateWalletPortfolioResponse, error)
	mustEmbedUnimplementedScannerWalletServer()
}

// UnimplementedScannerWalletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerWalletServer struct{}

func (UnimplementedScannerWalletServer) AddWallet(context.Context, *AddWalletRequest) (*AddWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWallet not implemented")
}
func (UnimplementedScannerWalletServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedScannerWalletServer) GetWalletTokens(context.Context, *GetWalletTokensRequest) (*GetWalletTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletTokens not implemented")
}
func (UnimplementedScannerWalletServer) GetWalletDetails(context.Context, *GetWalletDetailsRequest) (*GetWalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletDetails not implemented")
}
func (UnimplementedScannerWalletServer) UpdateWalletPortfolio(context.Context, *UpdateWalletPortfolioRequest) (*UpdateWalletPortfolioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWalletPortfolio not implemented")
}
func (UnimplementedScannerWalletServer) mustEmbedUnimplementedScannerWalletServer() {}
func (UnimplementedScannerWalletServer) testEmbeddedByValue()                       {}

// UnsafeScannerWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerWalletServer will
// result in compilation errors.
type UnsafeScannerWalletServer interface {
	mustEmbedUnimplementedScannerWalletServer()
}

func RegisterScannerWalletServer(s grpc.ServiceRegistrar, srv ScannerWalletServer) {
	// If the following call panics, it indicates UnimplementedScannerWalletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScannerWallet_ServiceDesc, srv)
}

func _ScannerWallet_AddWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerWalletServer).AddWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerWallet_AddWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerWalletServer).AddWallet(ctx, req.(*AddWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerWallet_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerWalletServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerWallet_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerWalletServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerWallet_GetWalletTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerWalletServer).GetWalletTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerWallet_GetWalletTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerWalletServer).GetWalletTokens(ctx, req.(*GetWalletTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerWallet_GetWalletDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerWalletServer).GetWalletDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerWallet_GetWalletDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerWalletServer).GetWalletDetails(ctx, req.(*GetWalletDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerWallet_UpdateWalletPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWalletPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerWalletServer).UpdateWalletPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerWallet_UpdateWalletPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerWalletServer).UpdateWalletPortfolio(ctx, req.(*UpdateWalletPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScannerWallet_ServiceDesc is the grpc.ServiceDesc for ScannerWallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScannerWallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner_wallet.ScannerWallet",
	HandlerType: (*ScannerWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addWallet",
			Handler:    _ScannerWallet_AddWallet_Handler,
		},
		{
			MethodName: "getWallet",
			Handler:    _ScannerWallet_GetWallet_Handler,
		},
		{
			MethodName: "getWalletTokens",
			Handler:    _ScannerWallet_GetWalletTokens_Handler,
		},
		{
			MethodName: "getWalletDetails",
			Handler:    _ScannerWallet_GetWalletDetails_Handler,
		},
		{
			MethodName: "updateWalletPortfolio",
			Handler:    _ScannerWallet_UpdateWalletPortfolio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet/wallet.proto",
}
