// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: wallet/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wallet_wallet_proto protoreflect.FileDescriptor

const file_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	"\x13wallet/wallet.proto\x12\x0escanner_wallet\x1a\x15wallet/messages.proto2\xa4\x03\n" +
	"\rScannerWallet\x12@\n" +
	"\taddWallet\x12\x18.wallet.AddWalletRequest\x1a\x19.wallet.AddWalletResponse\x12@\n" +
	"\tgetWallet\x12\x18.wallet.GetWalletRequest\x1a\x19.wallet.GetWalletResponse\x12R\n" +
	"\x0fgetWalletTokens\x12\x1e.wallet.GetWalletTokensRequest\x1a\x1f.wallet.GetWalletTokensResponse\x12U\n" +
	"\x10getWalletDetails\x12\x1f.wallet.GetWalletDetailsRequest\x1a .wallet.GetWalletDetailsResponse\x12d\n" +
	"\x15updateWalletPortfolio\x12$.wallet.UpdateWalletPortfolioRequest\x1a%.wallet.UpdateWalletPortfolioResponseB\x19Z\x17walletdata/proto/walletb\x06proto3"

var file_wallet_wallet_proto_goTypes = []any{
	(*AddWalletRequest)(nil),              // 0: wallet.AddWalletRequest
	(*GetWalletRequest)(nil),              // 1: wallet.GetWalletRequest
	(*GetWalletTokensRequest)(nil),        // 2: wallet.GetWalletTokensRequest
	(*GetWalletDetailsRequest)(nil),       // 3: wallet.GetWalletDetailsRequest
	(*UpdateWalletPortfolioRequest)(nil),  // 4: wallet.UpdateWalletPortfolioRequest
	(*AddWalletResponse)(nil),             // 5: wallet.AddWalletResponse
	(*GetWalletResponse)(nil),             // 6: wallet.GetWalletResponse
	(*GetWalletTokensResponse)(nil),       // 7: wallet.GetWalletTokensResponse
	(*GetWalletDetailsResponse)(nil),      // 8: wallet.GetWalletDetailsResponse
	(*UpdateWalletPortfolioResponse)(nil), // 9: wallet.UpdateWalletPortfolioResponse
}
var file_wallet_wallet_proto_depIdxs = []int32{
	0, // 0: scanner_wallet.ScannerWallet.addWallet:input_type -> wallet.AddWalletRequest
	1, // 1: scanner_wallet.ScannerWallet.getWallet:input_type -> wallet.GetWalletRequest
	2, // 2: scanner_wallet.ScannerWallet.getWalletTokens:input_type -> wallet.GetWalletTokensRequest
	3, // 3: scanner_wallet.ScannerWallet.getWalletDetails:input_type -> wallet.GetWalletDetailsRequest
	4, // 4: scanner_wallet.ScannerWallet.updateWalletPortfolio:input_type -> wallet.UpdateWalletPortfolioRequest
	5, // 5: scanner_wallet.ScannerWallet.addWallet:output_type -> wallet.AddWalletResponse
	6, // 6: scanner_wallet.ScannerWallet.getWallet:output_type -> wallet.GetWalletResponse
	7, // 7: scanner_wallet.ScannerWallet.getWalletTokens:output_type -> wallet.GetWalletTokensResponse
	8, // 8: scanner_wallet.ScannerWallet.getWalletDetails:output_type -> wallet.GetWalletDetailsResponse
	9, // 9: scanner_wallet.ScannerWallet.updateWalletPortfolio:output_type -> wallet.UpdateWalletPortfolioResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_wallet_proto_init() }
func file_wallet_wallet_proto_init() {
	if File_wallet_wallet_proto != nil {
		return
	}
	file_wallet_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_wallet_proto_rawDesc), len(file_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_wallet_proto_depIdxs,
	}.Build()
	File_wallet_wallet_proto = out.File
	file_wallet_wallet_proto_goTypes = nil
	file_wallet_wallet_proto_depIdxs = nil
}
