// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: token/messages.proto

/* eslint-disable */
import { Token } from "../common/common";

export const protobufPackage = "token";

export enum TokenAddingType {
  DUPLICATE = "DUPLICATE",
  FIRST_TIME = "FIRST_TIME",
  ADD_ERROR = "ADD_ERROR",
}

export enum TokenRemovingType {
  STILL_CALCULATES = "STILL_CALCULATES",
  ALL_CLEAR = "ALL_CLEAR",
  REMOVE_ERROR = "REMOVE_ERROR",
}

export interface AddTokenRequest {
  tokenAddress: string;
  name?: string | undefined;
  symbol?: string | undefined;
  image?: string | undefined;
  poolAddress?: string | undefined;
  circulatedSupply?: string | undefined;
  pairAddress?: string | undefined;
  reason?: string | undefined;
  initialPrice?: string | undefined;
}

export interface AddTokenResponse {
  success: boolean;
  type: TokenAddingType;
  Message: string;
}

export interface GetTokenRequest {
  tokenAddress: string;
  addIfNotExist: boolean;
}

export interface GetTokenPriceRequest {
  tokenAddress: string;
  reason?: string | undefined;
}

export interface GetTokenPriceResponse {
  success: boolean;
  price: string;
  volume: string;
}

export interface GetTokenResponse {
  token: Token | undefined;
}

export interface RemoveTokenRequest {
  tokenAddress: string;
  bypassEnds?: boolean | undefined;
}

export interface RemoveTokenResponse {
  success: boolean;
  type: TokenRemovingType;
  Message: string;
}

export interface GetTokensRequest {
  tokenAddresses: string[];
}

export interface GetTokensResponse {
  tokens: Token[];
}

export interface AddBlacklistRequest {
  tokenAddresses: string[];
}

export interface AddBlacklistResponse {
  success: boolean;
}

export const TOKEN_PACKAGE_NAME = "token";
