// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: token/token.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  AddBlacklistRequest,
  AddBlacklistResponse,
  AddTokenRequest,
  AddTokenResponse,
  GetTokenPriceRequest,
  GetTokenPriceResponse,
  GetTokenRequest,
  GetTokenResponse,
  GetTokensRequest,
  GetTokensResponse,
  RemoveTokenRequest,
  RemoveTokenResponse,
} from "./messages";

export const protobufPackage = "scanner_token";

export const SCANNER_TOKEN_PACKAGE_NAME = "scanner_token";

export interface ScannerTokenClient {
  getToken(request: GetTokenRequest): Observable<GetTokenResponse>;

  getTokens(request: GetTokensRequest): Observable<GetTokensResponse>;

  getTokenPrice(request: GetTokenPriceRequest): Observable<GetTokenPriceResponse>;

  addToken(request: AddTokenRequest): Observable<AddTokenResponse>;

  removeToken(request: RemoveTokenRequest): Observable<RemoveTokenResponse>;

  addBlacklist(request: AddBlacklistRequest): Observable<AddBlacklistResponse>;
}

export interface ScannerTokenController {
  getToken(request: GetTokenRequest): Promise<GetTokenResponse> | Observable<GetTokenResponse> | GetTokenResponse;

  getTokens(request: GetTokensRequest): Promise<GetTokensResponse> | Observable<GetTokensResponse> | GetTokensResponse;

  getTokenPrice(
    request: GetTokenPriceRequest,
  ): Promise<GetTokenPriceResponse> | Observable<GetTokenPriceResponse> | GetTokenPriceResponse;

  addToken(request: AddTokenRequest): Promise<AddTokenResponse> | Observable<AddTokenResponse> | AddTokenResponse;

  removeToken(
    request: RemoveTokenRequest,
  ): Promise<RemoveTokenResponse> | Observable<RemoveTokenResponse> | RemoveTokenResponse;

  addBlacklist(
    request: AddBlacklistRequest,
  ): Promise<AddBlacklistResponse> | Observable<AddBlacklistResponse> | AddBlacklistResponse;
}

export function ScannerTokenControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getToken", "getTokens", "getTokenPrice", "addToken", "removeToken", "addBlacklist"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ScannerToken", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ScannerToken", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SCANNER_TOKEN_SERVICE_NAME = "ScannerToken";
