// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: common/common.proto

/* eslint-disable */

export const protobufPackage = "common";

export enum CHAIN {
  BASE = "BASE",
}

export interface Token {
  name: string;
  symbol: string;
  price: string;
  volume: string;
  calculatedVolume: string;
  imageUrl: string;
  address: string;
  poolAddress: string;
  supply: string;
  circulatedSupply: string;
  pairAddress: string;
  reason: string;
}

export interface Wallet {
  walletAddress: string;
  totalDollarValue: string;
  nativeBalance: string;
  nativeBalanceFormatted: string;
  tokenAddresses: string[];
}

export interface WalletToken {
  tokenAddress: string;
  tokenBalance: string;
  tokenBalanceFormatted: string;
  tokenPrice: string;
  tokenDollarValue: string;
  tokenImage: string;
  tokenName: string;
  tokenSymbol: string;
  tokenVolume: string;
  tokenSupply: string;
  tokenPairAddress: string;
}

export const COMMON_PACKAGE_NAME = "common";
