// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: index.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  AddTokenRequest,
  AddTokenResponse,
  GetTokenPriceRequest,
  GetTokenPriceResponse,
  GetTokenRequest,
  GetTokenResponse,
  RemoveTokenRequest,
  RemoveTokenResponse,
} from "./token/messages";
import {
  AddWalletRequest,
  AddWalletResponse,
  GetWalletDetailsRequest,
  GetWalletDetailsResponse,
  GetWalletRequest,
  GetWalletResponse,
  GetWalletTokensRequest,
  GetWalletTokensResponse,
} from "./wallet/messages";

export const protobufPackage = "scanner";

export const SCANNER_PACKAGE_NAME = "scanner";

export interface ScannerClient {
  /** Token operations */

  getToken(request: GetTokenRequest): Observable<GetTokenResponse>;

  getTokenPrice(request: GetTokenPriceRequest): Observable<GetTokenPriceResponse>;

  addToken(request: AddTokenRequest): Observable<AddTokenResponse>;

  removeToken(request: RemoveTokenRequest): Observable<RemoveTokenResponse>;

  /** Wallet operations */

  addWallet(request: AddWalletRequest): Observable<AddWalletResponse>;

  getWallet(request: GetWalletRequest): Observable<GetWalletResponse>;

  getWalletTokens(request: GetWalletTokensRequest): Observable<GetWalletTokensResponse>;

  getWalletDetails(request: GetWalletDetailsRequest): Observable<GetWalletDetailsResponse>;
}

export interface ScannerController {
  /** Token operations */

  getToken(request: GetTokenRequest): Promise<GetTokenResponse> | Observable<GetTokenResponse> | GetTokenResponse;

  getTokenPrice(
    request: GetTokenPriceRequest,
  ): Promise<GetTokenPriceResponse> | Observable<GetTokenPriceResponse> | GetTokenPriceResponse;

  addToken(request: AddTokenRequest): Promise<AddTokenResponse> | Observable<AddTokenResponse> | AddTokenResponse;

  removeToken(
    request: RemoveTokenRequest,
  ): Promise<RemoveTokenResponse> | Observable<RemoveTokenResponse> | RemoveTokenResponse;

  /** Wallet operations */

  addWallet(request: AddWalletRequest): Promise<AddWalletResponse> | Observable<AddWalletResponse> | AddWalletResponse;

  getWallet(request: GetWalletRequest): Promise<GetWalletResponse> | Observable<GetWalletResponse> | GetWalletResponse;

  getWalletTokens(
    request: GetWalletTokensRequest,
  ): Promise<GetWalletTokensResponse> | Observable<GetWalletTokensResponse> | GetWalletTokensResponse;

  getWalletDetails(
    request: GetWalletDetailsRequest,
  ): Promise<GetWalletDetailsResponse> | Observable<GetWalletDetailsResponse> | GetWalletDetailsResponse;
}

export function ScannerControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getToken",
      "getTokenPrice",
      "addToken",
      "removeToken",
      "addWallet",
      "getWallet",
      "getWalletTokens",
      "getWalletDetails",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Scanner", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Scanner", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SCANNER_SERVICE_NAME = "Scanner";
