// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: token/messages.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "walletdata/proto/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenAddingType int32

const (
	TokenAddingType_DUPLICATE  TokenAddingType = 0
	TokenAddingType_FIRST_TIME TokenAddingType = 1
	TokenAddingType_ADD_ERROR  TokenAddingType = 2
)

// Enum value maps for TokenAddingType.
var (
	TokenAddingType_name = map[int32]string{
		0: "DUPLICATE",
		1: "FIRST_TIME",
		2: "ADD_ERROR",
	}
	TokenAddingType_value = map[string]int32{
		"DUPLICATE":  0,
		"FIRST_TIME": 1,
		"ADD_ERROR":  2,
	}
)

func (x TokenAddingType) Enum() *TokenAddingType {
	p := new(TokenAddingType)
	*p = x
	return p
}

func (x TokenAddingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenAddingType) Descriptor() protoreflect.EnumDescriptor {
	return file_token_messages_proto_enumTypes[0].Descriptor()
}

func (TokenAddingType) Type() protoreflect.EnumType {
	return &file_token_messages_proto_enumTypes[0]
}

func (x TokenAddingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenAddingType.Descriptor instead.
func (TokenAddingType) EnumDescriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{0}
}

type TokenRemovingType int32

const (
	TokenRemovingType_STILL_CALCULATES TokenRemovingType = 0
	TokenRemovingType_ALL_CLEAR        TokenRemovingType = 1
	TokenRemovingType_REMOVE_ERROR     TokenRemovingType = 2
)

// Enum value maps for TokenRemovingType.
var (
	TokenRemovingType_name = map[int32]string{
		0: "STILL_CALCULATES",
		1: "ALL_CLEAR",
		2: "REMOVE_ERROR",
	}
	TokenRemovingType_value = map[string]int32{
		"STILL_CALCULATES": 0,
		"ALL_CLEAR":        1,
		"REMOVE_ERROR":     2,
	}
)

func (x TokenRemovingType) Enum() *TokenRemovingType {
	p := new(TokenRemovingType)
	*p = x
	return p
}

func (x TokenRemovingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenRemovingType) Descriptor() protoreflect.EnumDescriptor {
	return file_token_messages_proto_enumTypes[1].Descriptor()
}

func (TokenRemovingType) Type() protoreflect.EnumType {
	return &file_token_messages_proto_enumTypes[1]
}

func (x TokenRemovingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenRemovingType.Descriptor instead.
func (TokenRemovingType) EnumDescriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{1}
}

type AddTokenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress     string                 `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Symbol           *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Image            *string                `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	PoolAddress      *string                `protobuf:"bytes,5,opt,name=poolAddress,proto3,oneof" json:"poolAddress,omitempty"`
	CirculatedSupply *string                `protobuf:"bytes,6,opt,name=circulatedSupply,proto3,oneof" json:"circulatedSupply,omitempty"`
	PairAddress      *string                `protobuf:"bytes,7,opt,name=pairAddress,proto3,oneof" json:"pairAddress,omitempty"`
	Reason           *string                `protobuf:"bytes,8,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	InitialPrice     *string                `protobuf:"bytes,9,opt,name=initialPrice,proto3,oneof" json:"initialPrice,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddTokenRequest) Reset() {
	*x = AddTokenRequest{}
	mi := &file_token_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTokenRequest) ProtoMessage() {}

func (x *AddTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTokenRequest.ProtoReflect.Descriptor instead.
func (*AddTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AddTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *AddTokenRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AddTokenRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *AddTokenRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *AddTokenRequest) GetPoolAddress() string {
	if x != nil && x.PoolAddress != nil {
		return *x.PoolAddress
	}
	return ""
}

func (x *AddTokenRequest) GetCirculatedSupply() string {
	if x != nil && x.CirculatedSupply != nil {
		return *x.CirculatedSupply
	}
	return ""
}

func (x *AddTokenRequest) GetPairAddress() string {
	if x != nil && x.PairAddress != nil {
		return *x.PairAddress
	}
	return ""
}

func (x *AddTokenRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *AddTokenRequest) GetInitialPrice() string {
	if x != nil && x.InitialPrice != nil {
		return *x.InitialPrice
	}
	return ""
}

type AddTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Type          TokenAddingType        `protobuf:"varint,2,opt,name=type,proto3,enum=token.TokenAddingType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTokenResponse) Reset() {
	*x = AddTokenResponse{}
	mi := &file_token_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTokenResponse) ProtoMessage() {}

func (x *AddTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTokenResponse.ProtoReflect.Descriptor instead.
func (*AddTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AddTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTokenResponse) GetType() TokenAddingType {
	if x != nil {
		return x.Type
	}
	return TokenAddingType_DUPLICATE
}

func (x *AddTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	AddIfNotExist bool                   `protobuf:"varint,2,opt,name=addIfNotExist,proto3" json:"addIfNotExist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_token_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetTokenRequest) GetAddIfNotExist() bool {
	if x != nil {
		return x.AddIfNotExist
	}
	return false
}

type GetTokenPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPriceRequest) Reset() {
	*x = GetTokenPriceRequest{}
	mi := &file_token_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPriceRequest) ProtoMessage() {}

func (x *GetTokenPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPriceRequest.ProtoReflect.Descriptor instead.
func (*GetTokenPriceRequest) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenPriceRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetTokenPriceRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type GetTokenPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume        string                 `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPriceResponse) Reset() {
	*x = GetTokenPriceResponse{}
	mi := &file_token_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPriceResponse) ProtoMessage() {}

func (x *GetTokenPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPriceResponse.ProtoReflect.Descriptor instead.
func (*GetTokenPriceResponse) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenPriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTokenPriceResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetTokenPriceResponse) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *common.Token          `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_token_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetTokenResponse) GetToken() *common.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type RemoveTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	BypassEnds    *bool                  `protobuf:"varint,2,opt,name=bypassEnds,proto3,oneof" json:"bypassEnds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTokenRequest) Reset() {
	*x = RemoveTokenRequest{}
	mi := &file_token_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTokenRequest) ProtoMessage() {}

func (x *RemoveTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTokenRequest.ProtoReflect.Descriptor instead.
func (*RemoveTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *RemoveTokenRequest) GetBypassEnds() bool {
	if x != nil && x.BypassEnds != nil {
		return *x.BypassEnds
	}
	return false
}

type RemoveTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Type          TokenRemovingType      `protobuf:"varint,2,opt,name=type,proto3,enum=token.TokenRemovingType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTokenResponse) Reset() {
	*x = RemoveTokenResponse{}
	mi := &file_token_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTokenResponse) ProtoMessage() {}

func (x *RemoveTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTokenResponse.ProtoReflect.Descriptor instead.
func (*RemoveTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveTokenResponse) GetType() TokenRemovingType {
	if x != nil {
		return x.Type
	}
	return TokenRemovingType_STILL_CALCULATES
}

func (x *RemoveTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TokenAddresses []string               `protobuf:"bytes,1,rep,name=tokenAddresses,proto3" json:"tokenAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTokensRequest) Reset() {
	*x = GetTokensRequest{}
	mi := &file_token_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokensRequest) ProtoMessage() {}

func (x *GetTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokensRequest.ProtoReflect.Descriptor instead.
func (*GetTokensRequest) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetTokensRequest) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

type GetTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*common.Token        `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokensResponse) Reset() {
	*x = GetTokensResponse{}
	mi := &file_token_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokensResponse) ProtoMessage() {}

func (x *GetTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokensResponse.ProtoReflect.Descriptor instead.
func (*GetTokensResponse) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetTokensResponse) GetTokens() []*common.Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type AddBlacklistRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TokenAddresses []string               `protobuf:"bytes,1,rep,name=tokenAddresses,proto3" json:"tokenAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddBlacklistRequest) Reset() {
	*x = AddBlacklistRequest{}
	mi := &file_token_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistRequest) ProtoMessage() {}

func (x *AddBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{10}
}

func (x *AddBlacklistRequest) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

type AddBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistResponse) Reset() {
	*x = AddBlacklistResponse{}
	mi := &file_token_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistResponse) ProtoMessage() {}

func (x *AddBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistResponse.ProtoReflect.Descriptor instead.
func (*AddBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_token_messages_proto_rawDescGZIP(), []int{11}
}

func (x *AddBlacklistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_token_messages_proto protoreflect.FileDescriptor

const file_token_messages_proto_rawDesc = "" +
	"\n" +
	"\x14token/messages.proto\x12\x05token\x1a\x13common/common.proto\"\xba\x03\n" +
	"\x0fAddTokenRequest\x12\"\n" +
	"\ftokenAddress\x18\x01 \x01(\tR\ftokenAddress\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x04 \x01(\tH\x02R\x05image\x88\x01\x01\x12%\n" +
	"\vpoolAddress\x18\x05 \x01(\tH\x03R\vpoolAddress\x88\x01\x01\x12/\n" +
	"\x10circulatedSupply\x18\x06 \x01(\tH\x04R\x10circulatedSupply\x88\x01\x01\x12%\n" +
	"\vpairAddress\x18\a \x01(\tH\x05R\vpairAddress\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\b \x01(\tH\x06R\x06reason\x88\x01\x01\x12'\n" +
	"\finitialPrice\x18\t \x01(\tH\aR\finitialPrice\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\b\n" +
	"\x06_imageB\x0e\n" +
	"\f_poolAddressB\x13\n" +
	"\x11_circulatedSupplyB\x0e\n" +
	"\f_pairAddressB\t\n" +
	"\a_reasonB\x0f\n" +
	"\r_initialPrice\"r\n" +
	"\x10AddTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.token.TokenAddingTypeR\x04type\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"[\n" +
	"\x0fGetTokenRequest\x12\"\n" +
	"\ftokenAddress\x18\x01 \x01(\tR\ftokenAddress\x12$\n" +
	"\raddIfNotExist\x18\x02 \x01(\bR\raddIfNotExist\"b\n" +
	"\x14GetTokenPriceRequest\x12\"\n" +
	"\ftokenAddress\x18\x01 \x01(\tR\ftokenAddress\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"_\n" +
	"\x15GetTokenPriceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\tR\x06volume\"7\n" +
	"\x10GetTokenResponse\x12#\n" +
	"\x05token\x18\x01 \x01(\v2\r.common.TokenR\x05token\"l\n" +
	"\x12RemoveTokenRequest\x12\"\n" +
	"\ftokenAddress\x18\x01 \x01(\tR\ftokenAddress\x12#\n" +
	"\n" +
	"bypassEnds\x18\x02 \x01(\bH\x00R\n" +
	"bypassEnds\x88\x01\x01B\r\n" +
	"\v_bypassEnds\"w\n" +
	"\x13RemoveTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.token.TokenRemovingTypeR\x04type\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\":\n" +
	"\x10GetTokensRequest\x12&\n" +
	"\x0etokenAddresses\x18\x01 \x03(\tR\x0etokenAddresses\":\n" +
	"\x11GetTokensResponse\x12%\n" +
	"\x06tokens\x18\x01 \x03(\v2\r.common.TokenR\x06tokens\"=\n" +
	"\x13AddBlacklistRequest\x12&\n" +
	"\x0etokenAddresses\x18\x01 \x03(\tR\x0etokenAddresses\"0\n" +
	"\x14AddBlacklistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*?\n" +
	"\x0fTokenAddingType\x12\r\n" +
	"\tDUPLICATE\x10\x00\x12\x0e\n" +
	"\n" +
	"FIRST_TIME\x10\x01\x12\r\n" +
	"\tADD_ERROR\x10\x02*J\n" +
	"\x11TokenRemovingType\x12\x14\n" +
	"\x10STILL_CALCULATES\x10\x00\x12\r\n" +
	"\tALL_CLEAR\x10\x01\x12\x10\n" +
	"\fREMOVE_ERROR\x10\x02B\x17Z\x15tokendata/proto/tokenb\x06proto3"

var (
	file_token_messages_proto_rawDescOnce sync.Once
	file_token_messages_proto_rawDescData []byte
)

func file_token_messages_proto_rawDescGZIP() []byte {
	file_token_messages_proto_rawDescOnce.Do(func() {
		file_token_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_messages_proto_rawDesc), len(file_token_messages_proto_rawDesc)))
	})
	return file_token_messages_proto_rawDescData
}

var file_token_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_token_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_token_messages_proto_goTypes = []any{
	(TokenAddingType)(0),          // 0: token.TokenAddingType
	(TokenRemovingType)(0),        // 1: token.TokenRemovingType
	(*AddTokenRequest)(nil),       // 2: token.AddTokenRequest
	(*AddTokenResponse)(nil),      // 3: token.AddTokenResponse
	(*GetTokenRequest)(nil),       // 4: token.GetTokenRequest
	(*GetTokenPriceRequest)(nil),  // 5: token.GetTokenPriceRequest
	(*GetTokenPriceResponse)(nil), // 6: token.GetTokenPriceResponse
	(*GetTokenResponse)(nil),      // 7: token.GetTokenResponse
	(*RemoveTokenRequest)(nil),    // 8: token.RemoveTokenRequest
	(*RemoveTokenResponse)(nil),   // 9: token.RemoveTokenResponse
	(*GetTokensRequest)(nil),      // 10: token.GetTokensRequest
	(*GetTokensResponse)(nil),     // 11: token.GetTokensResponse
	(*AddBlacklistRequest)(nil),   // 12: token.AddBlacklistRequest
	(*AddBlacklistResponse)(nil),  // 13: token.AddBlacklistResponse
	(*common.Token)(nil),          // 14: common.Token
}
var file_token_messages_proto_depIdxs = []int32{
	0,  // 0: token.AddTokenResponse.type:type_name -> token.TokenAddingType
	14, // 1: token.GetTokenResponse.token:type_name -> common.Token
	1,  // 2: token.RemoveTokenResponse.type:type_name -> token.TokenRemovingType
	14, // 3: token.GetTokensResponse.tokens:type_name -> common.Token
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_token_messages_proto_init() }
func file_token_messages_proto_init() {
	if File_token_messages_proto != nil {
		return
	}
	file_token_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_token_messages_proto_msgTypes[3].OneofWrappers = []any{}
	file_token_messages_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_messages_proto_rawDesc), len(file_token_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_messages_proto_goTypes,
		DependencyIndexes: file_token_messages_proto_depIdxs,
		EnumInfos:         file_token_messages_proto_enumTypes,
		MessageInfos:      file_token_messages_proto_msgTypes,
	}.Build()
	File_token_messages_proto = out.File
	file_token_messages_proto_goTypes = nil
	file_token_messages_proto_depIdxs = nil
}
