// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: token/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_token_token_proto protoreflect.FileDescriptor

const file_token_token_proto_rawDesc = "" +
	"\n" +
	"\x11token/token.proto\x12\rscanner_token\x1a\x14token/messages.proto2\xa3\x03\n" +
	"\fScannerToken\x12;\n" +
	"\bgetToken\x12\x16.token.GetTokenRequest\x1a\x17.token.GetTokenResponse\x12>\n" +
	"\tgetTokens\x12\x17.token.GetTokensRequest\x1a\x18.token.GetTokensResponse\x12J\n" +
	"\rgetTokenPrice\x12\x1b.token.GetTokenPriceRequest\x1a\x1c.token.GetTokenPriceResponse\x12;\n" +
	"\baddToken\x12\x16.token.AddTokenRequest\x1a\x17.token.AddTokenResponse\x12D\n" +
	"\vremoveToken\x12\x19.token.RemoveTokenRequest\x1a\x1a.token.RemoveTokenResponse\x12G\n" +
	"\faddBlacklist\x12\x1a.token.AddBlacklistRequest\x1a\x1b.token.AddBlacklistResponseB\x17Z\x15tokendata/proto/tokenb\x06proto3"

var file_token_token_proto_goTypes = []any{
	(*GetTokenRequest)(nil),       // 0: token.GetTokenRequest
	(*GetTokensRequest)(nil),      // 1: token.GetTokensRequest
	(*GetTokenPriceRequest)(nil),  // 2: token.GetTokenPriceRequest
	(*AddTokenRequest)(nil),       // 3: token.AddTokenRequest
	(*RemoveTokenRequest)(nil),    // 4: token.RemoveTokenRequest
	(*AddBlacklistRequest)(nil),   // 5: token.AddBlacklistRequest
	(*GetTokenResponse)(nil),      // 6: token.GetTokenResponse
	(*GetTokensResponse)(nil),     // 7: token.GetTokensResponse
	(*GetTokenPriceResponse)(nil), // 8: token.GetTokenPriceResponse
	(*AddTokenResponse)(nil),      // 9: token.AddTokenResponse
	(*RemoveTokenResponse)(nil),   // 10: token.RemoveTokenResponse
	(*AddBlacklistResponse)(nil),  // 11: token.AddBlacklistResponse
}
var file_token_token_proto_depIdxs = []int32{
	0,  // 0: scanner_token.ScannerToken.getToken:input_type -> token.GetTokenRequest
	1,  // 1: scanner_token.ScannerToken.getTokens:input_type -> token.GetTokensRequest
	2,  // 2: scanner_token.ScannerToken.getTokenPrice:input_type -> token.GetTokenPriceRequest
	3,  // 3: scanner_token.ScannerToken.addToken:input_type -> token.AddTokenRequest
	4,  // 4: scanner_token.ScannerToken.removeToken:input_type -> token.RemoveTokenRequest
	5,  // 5: scanner_token.ScannerToken.addBlacklist:input_type -> token.AddBlacklistRequest
	6,  // 6: scanner_token.ScannerToken.getToken:output_type -> token.GetTokenResponse
	7,  // 7: scanner_token.ScannerToken.getTokens:output_type -> token.GetTokensResponse
	8,  // 8: scanner_token.ScannerToken.getTokenPrice:output_type -> token.GetTokenPriceResponse
	9,  // 9: scanner_token.ScannerToken.addToken:output_type -> token.AddTokenResponse
	10, // 10: scanner_token.ScannerToken.removeToken:output_type -> token.RemoveTokenResponse
	11, // 11: scanner_token.ScannerToken.addBlacklist:output_type -> token.AddBlacklistResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_token_token_proto_init() }
func file_token_token_proto_init() {
	if File_token_token_proto != nil {
		return
	}
	file_token_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_token_proto_rawDesc), len(file_token_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_token_proto_goTypes,
		DependencyIndexes: file_token_token_proto_depIdxs,
	}.Build()
	File_token_token_proto = out.File
	file_token_token_proto_goTypes = nil
	file_token_token_proto_depIdxs = nil
}
