// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: transactions.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "transactions";

export enum TransactionStatus {
  SUCCESS = "SUCCESS",
  FAIL = "FAIL",
  WAITING = "WAITING",
}

export interface LogTransactionRequest {
  txHash: string;
  connectionKey: string;
  connectionValue: string;
  transactionStatus: TransactionStatus;
  transactionParams?: { [key: string]: any } | undefined;
  transactionResultParams?: { [key: string]: any } | undefined;
  errorMessage?: string | undefined;
}

export interface LogTransactionResponse {
  saved: boolean;
}

export interface UpdateLoggedTransactionStatusRequest {
  txHash: string;
  transactionStatus: TransactionStatus;
  errorMessage?: string | undefined;
}

export interface UpdateLoggedTransactionStatusResponse {
  saved: boolean;
}

export const TRANSACTIONS_PACKAGE_NAME = "transactions";

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;

export interface TransactionServiceClient {
  logTransaction(request: LogTransactionRequest): Observable<LogTransactionResponse>;

  updateLoggedTransactionStatus(
    request: UpdateLoggedTransactionStatusRequest,
  ): Observable<UpdateLoggedTransactionStatusResponse>;
}

export interface TransactionServiceController {
  logTransaction(
    request: LogTransactionRequest,
  ): Promise<LogTransactionResponse> | Observable<LogTransactionResponse> | LogTransactionResponse;

  updateLoggedTransactionStatus(
    request: UpdateLoggedTransactionStatusRequest,
  ):
    | Promise<UpdateLoggedTransactionStatusResponse>
    | Observable<UpdateLoggedTransactionStatusResponse>
    | UpdateLoggedTransactionStatusResponse;
}

export function TransactionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["logTransaction", "updateLoggedTransactionStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TransactionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TransactionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRANSACTION_SERVICE_NAME = "TransactionService";
