// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: token/token.proto

package token

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScannerToken_GetToken_FullMethodName      = "/scanner_token.ScannerToken/getToken"
	ScannerToken_GetTokens_FullMethodName     = "/scanner_token.ScannerToken/getTokens"
	ScannerToken_GetTokenPrice_FullMethodName = "/scanner_token.ScannerToken/getTokenPrice"
	ScannerToken_AddToken_FullMethodName      = "/scanner_token.ScannerToken/addToken"
	ScannerToken_RemoveToken_FullMethodName   = "/scanner_token.ScannerToken/removeToken"
	ScannerToken_AddBlacklist_FullMethodName  = "/scanner_token.ScannerToken/addBlacklist"
)

// ScannerTokenClient is the client API for ScannerToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerTokenClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	GetTokens(ctx context.Context, in *GetTokensRequest, opts ...grpc.CallOption) (*GetTokensResponse, error)
	GetTokenPrice(ctx context.Context, in *GetTokenPriceRequest, opts ...grpc.CallOption) (*GetTokenPriceResponse, error)
	AddToken(ctx context.Context, in *AddTokenRequest, opts ...grpc.CallOption) (*AddTokenResponse, error)
	RemoveToken(ctx context.Context, in *RemoveTokenRequest, opts ...grpc.CallOption) (*RemoveTokenResponse, error)
	AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*AddBlacklistResponse, error)
}

type scannerTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerTokenClient(cc grpc.ClientConnInterface) ScannerTokenClient {
	return &scannerTokenClient{cc}
}

func (c *scannerTokenClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, ScannerToken_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerTokenClient) GetTokens(ctx context.Context, in *GetTokensRequest, opts ...grpc.CallOption) (*GetTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokensResponse)
	err := c.cc.Invoke(ctx, ScannerToken_GetTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerTokenClient) GetTokenPrice(ctx context.Context, in *GetTokenPriceRequest, opts ...grpc.CallOption) (*GetTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenPriceResponse)
	err := c.cc.Invoke(ctx, ScannerToken_GetTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerTokenClient) AddToken(ctx context.Context, in *AddTokenRequest, opts ...grpc.CallOption) (*AddTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTokenResponse)
	err := c.cc.Invoke(ctx, ScannerToken_AddToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerTokenClient) RemoveToken(ctx context.Context, in *RemoveTokenRequest, opts ...grpc.CallOption) (*RemoveTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTokenResponse)
	err := c.cc.Invoke(ctx, ScannerToken_RemoveToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerTokenClient) AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*AddBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBlacklistResponse)
	err := c.cc.Invoke(ctx, ScannerToken_AddBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerTokenServer is the server API for ScannerToken service.
// All implementations must embed UnimplementedScannerTokenServer
// for forward compatibility.
type ScannerTokenServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	GetTokens(context.Context, *GetTokensRequest) (*GetTokensResponse, error)
	GetTokenPrice(context.Context, *GetTokenPriceRequest) (*GetTokenPriceResponse, error)
	AddToken(context.Context, *AddTokenRequest) (*AddTokenResponse, error)
	RemoveToken(context.Context, *RemoveTokenRequest) (*RemoveTokenResponse, error)
	AddBlacklist(context.Context, *AddBlacklistRequest) (*AddBlacklistResponse, error)
	mustEmbedUnimplementedScannerTokenServer()
}

// UnimplementedScannerTokenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerTokenServer struct{}

func (UnimplementedScannerTokenServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedScannerTokenServer) GetTokens(context.Context, *GetTokensRequest) (*GetTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokens not implemented")
}
func (UnimplementedScannerTokenServer) GetTokenPrice(context.Context, *GetTokenPriceRequest) (*GetTokenPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenPrice not implemented")
}
func (UnimplementedScannerTokenServer) AddToken(context.Context, *AddTokenRequest) (*AddTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToken not implemented")
}
func (UnimplementedScannerTokenServer) RemoveToken(context.Context, *RemoveTokenRequest) (*RemoveTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveToken not implemented")
}
func (UnimplementedScannerTokenServer) AddBlacklist(context.Context, *AddBlacklistRequest) (*AddBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlacklist not implemented")
}
func (UnimplementedScannerTokenServer) mustEmbedUnimplementedScannerTokenServer() {}
func (UnimplementedScannerTokenServer) testEmbeddedByValue()                      {}

// UnsafeScannerTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerTokenServer will
// result in compilation errors.
type UnsafeScannerTokenServer interface {
	mustEmbedUnimplementedScannerTokenServer()
}

func RegisterScannerTokenServer(s grpc.ServiceRegistrar, srv ScannerTokenServer) {
	// If the following call panics, it indicates UnimplementedScannerTokenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScannerToken_ServiceDesc, srv)
}

func _ScannerToken_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerTokenServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerToken_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerTokenServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerToken_GetTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerTokenServer).GetTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerToken_GetTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerTokenServer).GetTokens(ctx, req.(*GetTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerToken_GetTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerTokenServer).GetTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerToken_GetTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerTokenServer).GetTokenPrice(ctx, req.(*GetTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerToken_AddToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerTokenServer).AddToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerToken_AddToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerTokenServer).AddToken(ctx, req.(*AddTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerToken_RemoveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerTokenServer).RemoveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerToken_RemoveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerTokenServer).RemoveToken(ctx, req.(*RemoveTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerToken_AddBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerTokenServer).AddBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerToken_AddBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerTokenServer).AddBlacklist(ctx, req.(*AddBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScannerToken_ServiceDesc is the grpc.ServiceDesc for ScannerToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScannerToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner_token.ScannerToken",
	HandlerType: (*ScannerTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getToken",
			Handler:    _ScannerToken_GetToken_Handler,
		},
		{
			MethodName: "getTokens",
			Handler:    _ScannerToken_GetTokens_Handler,
		},
		{
			MethodName: "getTokenPrice",
			Handler:    _ScannerToken_GetTokenPrice_Handler,
		},
		{
			MethodName: "addToken",
			Handler:    _ScannerToken_AddToken_Handler,
		},
		{
			MethodName: "removeToken",
			Handler:    _ScannerToken_RemoveToken_Handler,
		},
		{
			MethodName: "addBlacklist",
			Handler:    _ScannerToken_AddBlacklist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token/token.proto",
}
