// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHAIN int32

const (
	CHAIN_BASE   CHAIN = 0
	CHAIN_SOLANA CHAIN = 1
)

// Enum value maps for CHAIN.
var (
	CHAIN_name = map[int32]string{
		0: "BASE",
		1: "SOLANA",
	}
	CHAIN_value = map[string]int32{
		"BASE":   0,
		"SOLANA": 1,
	}
)

func (x CHAIN) Enum() *CHAIN {
	p := new(CHAIN)
	*p = x
	return p
}

func (x CHAIN) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CHAIN) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (CHAIN) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x CHAIN) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CHAIN.Descriptor instead.
func (CHAIN) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

type Token struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol           string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price            string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Volume           string                 `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
	CalculatedVolume string                 `protobuf:"bytes,5,opt,name=calculatedVolume,proto3" json:"calculatedVolume,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Address          string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	PoolAddress      string                 `protobuf:"bytes,8,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	Supply           string                 `protobuf:"bytes,9,opt,name=supply,proto3" json:"supply,omitempty"`
	CirculatedSupply string                 `protobuf:"bytes,10,opt,name=circulatedSupply,proto3" json:"circulatedSupply,omitempty"`
	PairAddress      string                 `protobuf:"bytes,11,opt,name=pairAddress,proto3" json:"pairAddress,omitempty"`
	Reason           string                 `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Token) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Token) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Token) GetCalculatedVolume() string {
	if x != nil {
		return x.CalculatedVolume
	}
	return ""
}

func (x *Token) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *Token) GetSupply() string {
	if x != nil {
		return x.Supply
	}
	return ""
}

func (x *Token) GetCirculatedSupply() string {
	if x != nil {
		return x.CirculatedSupply
	}
	return ""
}

func (x *Token) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *Token) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Wallet struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress          string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	TotalDollarValue       string                 `protobuf:"bytes,2,opt,name=totalDollarValue,proto3" json:"totalDollarValue,omitempty"`
	NativeBalance          string                 `protobuf:"bytes,3,opt,name=nativeBalance,proto3" json:"nativeBalance,omitempty"`
	NativeBalanceFormatted string                 `protobuf:"bytes,4,opt,name=nativeBalanceFormatted,proto3" json:"nativeBalanceFormatted,omitempty"`
	TokenAddresses         []string               `protobuf:"bytes,5,rep,name=tokenAddresses,proto3" json:"tokenAddresses,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *Wallet) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *Wallet) GetTotalDollarValue() string {
	if x != nil {
		return x.TotalDollarValue
	}
	return ""
}

func (x *Wallet) GetNativeBalance() string {
	if x != nil {
		return x.NativeBalance
	}
	return ""
}

func (x *Wallet) GetNativeBalanceFormatted() string {
	if x != nil {
		return x.NativeBalanceFormatted
	}
	return ""
}

func (x *Wallet) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

type WalletToken struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress          string                 `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	TokenBalance          string                 `protobuf:"bytes,2,opt,name=tokenBalance,proto3" json:"tokenBalance,omitempty"`
	TokenBalanceFormatted string                 `protobuf:"bytes,3,opt,name=tokenBalanceFormatted,proto3" json:"tokenBalanceFormatted,omitempty"`
	TokenPrice            string                 `protobuf:"bytes,4,opt,name=tokenPrice,proto3" json:"tokenPrice,omitempty"`
	TokenDollarValue      string                 `protobuf:"bytes,5,opt,name=tokenDollarValue,proto3" json:"tokenDollarValue,omitempty"`
	TokenImage            string                 `protobuf:"bytes,6,opt,name=tokenImage,proto3" json:"tokenImage,omitempty"`
	TokenName             string                 `protobuf:"bytes,7,opt,name=tokenName,proto3" json:"tokenName,omitempty"`
	TokenSymbol           string                 `protobuf:"bytes,8,opt,name=tokenSymbol,proto3" json:"tokenSymbol,omitempty"`
	TokenVolume           string                 `protobuf:"bytes,9,opt,name=tokenVolume,proto3" json:"tokenVolume,omitempty"`
	TokenSupply           string                 `protobuf:"bytes,10,opt,name=tokenSupply,proto3" json:"tokenSupply,omitempty"`
	TokenPairAddress      string                 `protobuf:"bytes,11,opt,name=tokenPairAddress,proto3" json:"tokenPairAddress,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WalletToken) Reset() {
	*x = WalletToken{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletToken) ProtoMessage() {}

func (x *WalletToken) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletToken.ProtoReflect.Descriptor instead.
func (*WalletToken) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *WalletToken) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *WalletToken) GetTokenBalance() string {
	if x != nil {
		return x.TokenBalance
	}
	return ""
}

func (x *WalletToken) GetTokenBalanceFormatted() string {
	if x != nil {
		return x.TokenBalanceFormatted
	}
	return ""
}

func (x *WalletToken) GetTokenPrice() string {
	if x != nil {
		return x.TokenPrice
	}
	return ""
}

func (x *WalletToken) GetTokenDollarValue() string {
	if x != nil {
		return x.TokenDollarValue
	}
	return ""
}

func (x *WalletToken) GetTokenImage() string {
	if x != nil {
		return x.TokenImage
	}
	return ""
}

func (x *WalletToken) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *WalletToken) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *WalletToken) GetTokenVolume() string {
	if x != nil {
		return x.TokenVolume
	}
	return ""
}

func (x *WalletToken) GetTokenSupply() string {
	if x != nil {
		return x.TokenSupply
	}
	return ""
}

func (x *WalletToken) GetTokenPairAddress() string {
	if x != nil {
		return x.TokenPairAddress
	}
	return ""
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x06common\"\xe3\x02\n" +
	"\x05Token\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\tR\x06volume\x12*\n" +
	"\x10calculatedVolume\x18\x05 \x01(\tR\x10calculatedVolume\x12\x1a\n" +
	"\bimageUrl\x18\x06 \x01(\tR\bimageUrl\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12 \n" +
	"\vpoolAddress\x18\b \x01(\tR\vpoolAddress\x12\x16\n" +
	"\x06supply\x18\t \x01(\tR\x06supply\x12*\n" +
	"\x10circulatedSupply\x18\n" +
	" \x01(\tR\x10circulatedSupply\x12 \n" +
	"\vpairAddress\x18\v \x01(\tR\vpairAddress\x12\x16\n" +
	"\x06reason\x18\f \x01(\tR\x06reason\"\xe0\x01\n" +
	"\x06Wallet\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\x12*\n" +
	"\x10totalDollarValue\x18\x02 \x01(\tR\x10totalDollarValue\x12$\n" +
	"\rnativeBalance\x18\x03 \x01(\tR\rnativeBalance\x126\n" +
	"\x16nativeBalanceFormatted\x18\x04 \x01(\tR\x16nativeBalanceFormatted\x12&\n" +
	"\x0etokenAddresses\x18\x05 \x03(\tR\x0etokenAddresses\"\xa7\x03\n" +
	"\vWalletToken\x12\"\n" +
	"\ftokenAddress\x18\x01 \x01(\tR\ftokenAddress\x12\"\n" +
	"\ftokenBalance\x18\x02 \x01(\tR\ftokenBalance\x124\n" +
	"\x15tokenBalanceFormatted\x18\x03 \x01(\tR\x15tokenBalanceFormatted\x12\x1e\n" +
	"\n" +
	"tokenPrice\x18\x04 \x01(\tR\n" +
	"tokenPrice\x12*\n" +
	"\x10tokenDollarValue\x18\x05 \x01(\tR\x10tokenDollarValue\x12\x1e\n" +
	"\n" +
	"tokenImage\x18\x06 \x01(\tR\n" +
	"tokenImage\x12\x1c\n" +
	"\ttokenName\x18\a \x01(\tR\ttokenName\x12 \n" +
	"\vtokenSymbol\x18\b \x01(\tR\vtokenSymbol\x12 \n" +
	"\vtokenVolume\x18\t \x01(\tR\vtokenVolume\x12 \n" +
	"\vtokenSupply\x18\n" +
	" \x01(\tR\vtokenSupply\x12*\n" +
	"\x10tokenPairAddress\x18\v \x01(\tR\x10tokenPairAddress*\x1d\n" +
	"\x05CHAIN\x12\b\n" +
	"\x04BASE\x10\x00\x12\n" +
	"\n" +
	"\x06SOLANA\x10\x01B\x18Z\x16tokendata/proto/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_common_proto_goTypes = []any{
	(CHAIN)(0),          // 0: common.CHAIN
	(*Token)(nil),       // 1: common.Token
	(*Wallet)(nil),      // 2: common.Wallet
	(*WalletToken)(nil), // 3: common.WalletToken
}
var file_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
